//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public COURSE()
        {
            this.COMMENT = new HashSet<COMMENT>();
            this.ATTEND = new HashSet<ATTEND>();
            this.LESSON = new HashSet<LESSON>();
            this.RECOMMENDATION = new HashSet<RECOMMENDATION>();
            this.CUSTOMER1 = new HashSet<CUSTOMER>();
        }
    
        public int ID { get; set; }
        public decimal PRICE { get; set; }
        public Nullable<double> RATE { get; set; }
        public string TITLE { get; set; }
        public string INTRO { get; set; }
        public int TEACHER { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public string COURSE_STATUS { get; set; }
        public Nullable<int> PG { get; set; }
        public string ICON_URL { get; set; }
        public System.DateTime START_TIME { get; set; }
    
        public virtual CATEGORY CATEGORY1 { get; set; }
        public virtual ICollection<COMMENT> COMMENT { get; set; }
        public virtual ICollection<ATTEND> ATTEND { get; set; }
        public virtual PARENT_GUIDE PARENT_GUIDE { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual ICollection<LESSON> LESSON { get; set; }
        public virtual ICollection<RECOMMENDATION> RECOMMENDATION { get; set; }
        public virtual ICollection<CUSTOMER> CUSTOMER1 { get; set; }
    }
}
